name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install meson
      run: |
          sudo apt-get install python3-pip ninja-build
          sudo python3 -m pip install meson
    - name: compile & test
      run: |
          meson build
          cd build
          ninja
          ninja test
